version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      # Install packages or any pre-reqs in this phase.
      # Upgrading SAM CLI to latest version
      - pip3 install --upgrade aws-sam-cli
      - sam --version
      # Installing project dependencies
      #- cd hello-world
      #- npm install
  
  pre_build:
    commands:
      - echo $CODEBUILD_SOURCE_VERSION
      # Run tests, lint scripts or any other pre-build checks.
      # - npm run test

  build:
    commands:
      # Use Build phase to build your artifacts (compile, etc.)
      #- cd ..
      #- sam build
      - sam build --template-file template.yaml
      - pwd

  post_build:
    commands:
      # Use Post-Build for notifications, git tags, upload artifacts to S3
      - echo $PACKAGE_BUCKET
      #- sam package --s3-bucket $PACKAGE_BUCKET --output-template-file packaged.yaml
      - pwd
      - ls -la
      - sam package --help
      - aws cloudformation package --output-template-file packaged.yaml --s3-bucket $PACKAGE_BUCKET --template-file template.yaml --debug
      - cat packaged.yaml

artifacts:
  discard-paths: yes
  files:
    # List of local artifacts that will be passed down the pipeline
    - packaged.yaml